"""initial schema

Revision ID: d7f74156f7cb
Revises: 
Create Date: 2026-08-22 12:48:10.649246
"""
from alembic import op
import sqlalchemy as sa


revision = 'd7f74156f7cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_predictions',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('task', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('input_digest', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_predictions'))
    )
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_predictions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_predictions_subject_type'), ['subject_type'], unique=False)

    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_slug'), ['slug'], unique=True)

    op.create_table('facilities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('facility_type', sa.String(length=30), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('ward', sa.String(length=120), nullable=True),
    sa.Column('capacity_note', sa.String(length=300), nullable=True),
    sa.Column('service_level', sa.String(length=16), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facilities_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_facilities_facility_type'), ['facility_type'], unique=False)

    op.create_table('problem_clusters',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('representative_report_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Integer(), nullable=False),
    sa.Column('address_text', sa.String(length=300), nullable=True),
    sa.Column('ward', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_level', sa.String(length=12), nullable=False),
    sa.Column('priority_components', sa.JSON(), nullable=True),
    sa.Column('affected_population_est', sa.Integer(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('first_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_department_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_department_id'], ['departments.id'], name=op.f('fk_problem_clusters_assigned_department_id_departments')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_problem_clusters_category_id_categories')),
    sa.ForeignKeyConstraint(['representative_report_id'], ['reports.id'], name=op.f('fk_problem_clusters_representative_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_clusters'))
    )
    with op.batch_alter_table('problem_clusters', schema=None) as batch_op:
        batch_op.create_index('ix_clusters_latlng', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_clusters_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_clusters_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_problem_clusters_priority_level'), ['priority_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_clusters_priority_score'), ['priority_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_clusters_status'), ['status'], unique=False)

    op.create_table('reports',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('citizen_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('category_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('category_source', sa.String(length=20), nullable=False),
    sa.Column('ai_category_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_severity', sa.Integer(), nullable=True),
    sa.Column('ai_urgency', sa.Integer(), nullable=True),
    sa.Column('ai_keywords', sa.JSON(), nullable=True),
    sa.Column('ai_status', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('address_text', sa.String(length=300), nullable=True),
    sa.Column('landmark', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_source', sa.String(length=16), nullable=False),
    sa.Column('ward', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('additional_notes', sa.String(length=1000), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_category_id'], ['categories.id'], name=op.f('fk_reports_ai_category_id_categories')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_reports_category_id_categories')),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], name=op.f('fk_reports_citizen_id_users')),
    sa.ForeignKeyConstraint(['cluster_id'], ['problem_clusters.id'], name=op.f('fk_reports_cluster_id_problem_clusters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_code'), ['code'], unique=True)
        batch_op.create_index('ix_reports_created', ['created_at'], unique=False)
        batch_op.create_index('ix_reports_latlng', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('accessibility_gaps',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('area_label', sa.String(length=200), nullable=False),
    sa.Column('area_type', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('facility_type', sa.String(length=30), nullable=False),
    sa.Column('population_est', sa.Integer(), nullable=False),
    sa.Column('nearest_facility_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('nearest_facility_name', sa.String(length=200), nullable=True),
    sa.Column('nearest_distance_km', sa.Float(), nullable=True),
    sa.Column('gap_score', sa.Float(), nullable=False),
    sa.Column('severity_label', sa.String(length=12), nullable=False),
    sa.Column('insight_text', sa.String(length=1000), nullable=True),
    sa.Column('parameters_snapshot', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nearest_facility_id'], ['facilities.id'], name=op.f('fk_accessibility_gaps_nearest_facility_id_facilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accessibility_gaps'))
    )
    with op.batch_alter_table('accessibility_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accessibility_gaps_facility_type'), ['facility_type'], unique=False)

    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('department_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_categories_department_id_departments')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('cluster_reports',
    sa.Column('cluster_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('report_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['problem_clusters.id'], name=op.f('fk_cluster_reports_cluster_id_problem_clusters')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_cluster_reports_report_id_reports')),
    sa.PrimaryKeyConstraint('cluster_id', 'report_id', name=op.f('pk_cluster_reports')),
    sa.UniqueConstraint('cluster_id', 'report_id', name='uq_cluster_report')
    )
    op.create_table('report_media',
    sa.Column('report_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('processing_status', sa.String(length=16), nullable=False),
    sa.Column('ai_labels', sa.JSON(), nullable=True),
    sa.Column('created_by_role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_media_report_id_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_media'))
    )
    with op.batch_alter_table('report_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_media_report_id'), ['report_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('ward', sa.String(length=120), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('actions',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('cluster_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('department_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('officer_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('team_name', sa.String(length=150), nullable=True),
    sa.Column('resources_needed', sa.String(length=1000), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority_level_snapshot', sa.String(length=12), nullable=False),
    sa.Column('priority_score_snapshot', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_by_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['problem_clusters.id'], name=op.f('fk_actions_cluster_id_problem_clusters')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_actions_created_by_id_users')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_actions_department_id_departments')),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], name=op.f('fk_actions_officer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_actions_officer_id'), ['officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('actor_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('recipient_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_read_at'), ['read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('simulation_parameters',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_simulation_parameters_updated_by_id_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_simulation_parameters'))
    )
    op.create_table('action_resources',
    sa.Column('action_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_action_resources_action_id_actions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_resources'))
    )
    with op.batch_alter_table('action_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_resources_action_id'), ['action_id'], unique=False)

    op.create_table('resolution_evidence',
    sa.Column('action_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=False),
    sa.Column('completion_details', sa.String(length=2000), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('submitted_by_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_resolution_evidence_action_id_actions')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_resolution_evidence_submitted_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resolution_evidence'))
    )
    with op.batch_alter_table('resolution_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resolution_evidence_action_id'), ['action_id'], unique=False)

    op.create_table('verifications',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('cluster_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('action_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('citizen_id', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('verdict', sa.String(length=12), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_verifications_action_id_actions')),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], name=op.f('fk_verifications_citizen_id_users')),
    sa.ForeignKeyConstraint(['cluster_id'], ['problem_clusters.id'], name=op.f('fk_verifications_cluster_id_problem_clusters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verifications'))
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verifications_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verifications_cluster_id'), ['cluster_id'], unique=False)

    op.create_table('evidence_media',
    sa.Column('evidence_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('media_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['resolution_evidence.id'], name=op.f('fk_evidence_media_evidence_id_resolution_evidence')),
    sa.ForeignKeyConstraint(['media_id'], ['report_media.id'], name=op.f('fk_evidence_media_media_id_report_media')),
    sa.PrimaryKeyConstraint('evidence_id', 'media_id', name=op.f('pk_evidence_media')),
    sa.UniqueConstraint('evidence_id', 'media_id', name='uq_evidence_media')
    )
    # ### end Alembic commands ###

    # ---- PostGIS additions (PostgreSQL only) --------------------------------
    if op.get_bind().dialect.name == "postgresql":
        # Real geography columns generated from lat/lng + spatial indexes.
        for table in ("reports", "problem_clusters", "facilities", "accessibility_gaps"):
            op.execute(
                f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS geom "
                f"geography(Point, 4326) "
                f"GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED"
            )
            op.execute(f"CREATE INDEX IF NOT EXISTS ix_{table}_geom ON {table} USING GIST (geom)")


def downgrade() -> None:
    # ---- PostGIS teardown (PostgreSQL only) ---------------------------------
    if op.get_bind().dialect.name == "postgresql":
        for table in ("reports", "problem_clusters", "facilities", "accessibility_gaps"):
            op.execute(f"DROP INDEX IF EXISTS ix_{table}_geom")
        for table in ("reports", "problem_clusters", "facilities", "accessibility_gaps"):
            op.execute(f"ALTER TABLE {table} DROP COLUMN IF EXISTS geom")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_media')
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verifications_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_verifications_action_id'))

    op.drop_table('verifications')
    with op.batch_alter_table('resolution_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resolution_evidence_action_id'))

    op.drop_table('resolution_evidence')
    with op.batch_alter_table('action_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_resources_action_id'))

    op.drop_table('action_resources')
    op.drop_table('simulation_parameters')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_status'))
        batch_op.drop_index(batch_op.f('ix_actions_officer_id'))
        batch_op.drop_index(batch_op.f('ix_actions_code'))
        batch_op.drop_index(batch_op.f('ix_actions_cluster_id'))

    op.drop_table('actions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('report_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_media_report_id'))

    op.drop_table('report_media')
    op.drop_table('cluster_reports')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    with op.batch_alter_table('accessibility_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accessibility_gaps_facility_type'))

    op.drop_table('accessibility_gaps')
    op.drop_table('roles')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index('ix_reports_latlng')
        batch_op.drop_index('ix_reports_created')
        batch_op.drop_index(batch_op.f('ix_reports_code'))
        batch_op.drop_index(batch_op.f('ix_reports_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_reports_citizen_id'))
        batch_op.drop_index(batch_op.f('ix_reports_category_id'))

    op.drop_table('reports')
    with op.batch_alter_table('problem_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_clusters_status'))
        batch_op.drop_index(batch_op.f('ix_problem_clusters_priority_score'))
        batch_op.drop_index(batch_op.f('ix_problem_clusters_priority_level'))
        batch_op.drop_index(batch_op.f('ix_problem_clusters_code'))
        batch_op.drop_index(batch_op.f('ix_problem_clusters_category_id'))
        batch_op.drop_index('ix_clusters_latlng')

    op.drop_table('problem_clusters')
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facilities_facility_type'))
        batch_op.drop_index(batch_op.f('ix_facilities_district'))

    op.drop_table('facilities')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_slug'))

    op.drop_table('departments')
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_predictions_subject_type'))
        batch_op.drop_index(batch_op.f('ix_ai_predictions_subject_id'))

    op.drop_table('ai_predictions')
    # ### end Alembic commands ###
